### PR TITLE
translated to snakemake

### PR DESCRIPTION
**Pull request by dkoppstein**
I wasn't able to test this with input (I think you have `input` in your .gitignore =)) but I was able to test it using the --dryrun functionality of snakemake. 

All of these rules used the `shell:` command, but you can also execute arbitrary python code within rules using `run:`. For more examples, see [the snakemake homepage](https://bitbucket.org/johanneskoester/snakemake/wiki/Home). Thanks again for the great talk! 

```
(venv343) ➜  bulldozers git:(master) ✗ snakemake --dryrun --printshellcmds
rule clean_input:
    input: input/Train.csv, input/Machine_Appendix.csv, scripts/clean.R
    output: working/cleaned_input.csv
Rscript scripts/clean.R working/cleaned_input.csv input/Train.csv input/Machine_Appendix.csv
rule split:
    input: working/cleaned_input.csv, scripts/train_test_split.R
    output: working/split/test.csv, working/split/train.csv
Rscript scripts/train_test_split.R working/split/train.csv working/cleaned_input.csv
rule test_predictions:
    input: scripts/model.R, working/split/test.csv, working/split/train.csv
    output: working/models/lm/test_predictions.csv
Rscript scripts/model.R working/split/train.csv working/split/test.csv lm working/models/lm/test_predictions.csv
rule test_predictions:
    input: scripts/model.R, working/split/test.csv, working/split/train.csv
    output: working/models/rf/test_predictions.csv
Rscript scripts/model.R working/split/train.csv working/split/test.csv rf working/models/rf/test_predictions.csv
rule predicted_vs_actual:
    input: working/models/lm/test_predictions.csv, scripts/plot_predicted_vs_actual.R
    output: working/models/lm/predicted_vs_actual.png
Rscript working/models/lm/test_predictions.csv scripts/plot_predicted_vs_actual.R working/models/lm/predicted_vs_actual.png
rule model_performance:
    input: working/models/rf/test_predictions.csv, working/models/lm/test_predictions.csv, scripts/model_performance.R
    output: working/models/model_performance.png
Rscript scripts/model_performance.R working/models/rf/test_predictions.csv working/models/lm/test_predictions.csv working/models/model_performance.png
rule predicted_vs_actual:
    input: working/models/rf/test_predictions.csv, scripts/plot_predicted_vs_actual.R
    output: working/models/rf/predicted_vs_actual.png
Rscript working/models/rf/test_predictions.csv scripts/plot_predicted_vs_actual.R working/models/rf/predicted_vs_actual.png
rule all:
    input: working/models/model_performance.png, working/models/rf/test_predictions.csv, working/models/lm/test_predictions.csv, working/models/rf/predicted_vs_actual.png, working/models/lm/predicted_vs_actual.png
Rscript launch_app.R residuals "working/models/rf/test_predictions.csv working/models/lm/test_predictions.csv"
Job counts:
    count   jobs
    2   test_predictions
    2   predicted_vs_actual
    1   all
    1   clean_input
    1   split
    1   model_performance
    8
```

### CODE REVIEW

**Comment by dchudz** [comment]
Ah, sorry about the input data.  It's from here: https://www.kaggle.com/c/bluebook-for-bulldozers/data. I've updated the readme to point to it.

**Comment by dchudz** [comment]
this looks really nice. thanks!

**Comment by dchudz** [comment]
when I run it, I'm getting a problem with the train/test split step:

```
1 of 8 steps (12%) done
rule split:
    input: working/cleaned_input.csv, scripts/train_test_split.R
    output: working/split/test.csv, working/split/train.csv
Rscript scripts/train_test_split.R working/split/train.csv working/cleaned_input.csv

Attaching package: ‘dplyr’

The following object is masked from ‘package:stats’:

    filter

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

    Input arguments: c("working/split/train.csv", "working/cleaned_input.csv")
Waiting at most 5 seconds for missing files.
Error in job split while creating output files working/split/test.csv, working/split/train.csv.
MissingOutputException in line 61 of /Users/david/github/opendatascicon-2015-make/bulldozers/Snakefile:
Missing files after 5 seconds:
working/split/test.csv
Removing output files of failed job split since they might be corrupted:
working/split/train.csv
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```

The issue is that the R script needs to be different for make and snakemake. (With make, the command line argument to the script is the directory path. `working/split`. For snakemake, it'll be the files.

I think probably this means we should separate into two directories, `bulldozers/make` and `bulldozers/snakemake`.

**Comment by dchudz** [comment]
Ah, I think we could keep the R script the same for `make` and `snakemake` if we use your alternative rule...?

```
    outdir = dirname(output[0])
    shell('Rscript {input.script} {outdir} {input.csv')
```

**Comment by dkoppstein** [comment]
OK, I updated the rule -- it should work now. Regarding your question, snakemake uses time stamps like Make. The author of Snakemake, Johannes Koester, is very engaged and receptive to feedback -- if hashing the files is a feature you're looking for, I encourage you to contact him!

**Comment by dchudz** [comment]
Awesome, thanks!

**Comment by dchudz** [comment]
Other build tools might eventually motivate moving to a wholly separate folder for each tool, but for now keeping all of the scripts the same across the two makes sense I think.

**Pull request merged**
